/**
 * Password hashing.
 *
 * Two separate things are pinned here, and they fail in very different ways.
 *
 * 1. **Compatibility.** The project moved from `bcryptjs` to the native
 *    `bcrypt` binding for throughput. Both emit `$2b$` hashes and each can read
 *    the other's, which is the only reason the migration needed no password
 *    reset. If that ever stops being true, every account in the database is
 *    locked out at once — so a hash produced by the *old* library is checked in
 *    here as a fixture rather than generated, because a generated one would
 *    only ever prove the new library agrees with itself.
 *
 * 2. **The 72-byte limit.** bcrypt reads at most 72 bytes and discards the rest
 *    without error. That is a property of the algorithm, not of either library,
 *    so switching did not fix it and only a cap at the validation layer can.
 */
import { describe, expect, it } from "vitest";
import {
  comparePassword,
  hashPassword,
  MAX_PASSWORD_BYTES,
} from "../../src/shared/auth/password.helper";

// Generated by bcryptjs@3.0.3 at cost 12 for the password below, and committed
// as a literal so this stays a real cross-library check forever.
const LEGACY_BCRYPTJS_HASH =
  "$2b$12$f4d54lHOWDLqsbqZp.hZH.e05XR23T9NQHrDpBlLmcF.sN8gobly6";
const LEGACY_PASSWORD = "Passw0rd!23";

describe("hashes written by the previous library still work", () => {
  it("accepts the correct password against a bcryptjs hash", async () => {
    // The migration's whole safety claim, in one assertion.
    expect(await comparePassword(LEGACY_PASSWORD, LEGACY_BCRYPTJS_HASH)).toBe(
      true,
    );
  });

  it("still rejects a wrong password against that same hash", async () => {
    // Guards the failure mode where compare returns true for everything.
    expect(await comparePassword("wrong-password", LEGACY_BCRYPTJS_HASH)).toBe(
      false,
    );
  });
});

describe("hashing", () => {
  it("produces a $2b$ hash at cost 12", async () => {
    const hash = await hashPassword("some-password");

    // The cost is a security decision; a silent drop to the library default
    // would look identical everywhere except in this string.
    expect(hash.startsWith("$2b$12$")).toBe(true);
  });

  it("salts, so the same password never hashes twice the same way", async () => {
    const [a, b] = await Promise.all([
      hashPassword("same-password"),
      hashPassword("same-password"),
    ]);

    expect(a).not.toBe(b);
    expect(await comparePassword("same-password", a)).toBe(true);
    expect(await comparePassword("same-password", b)).toBe(true);
  });

  it("round-trips a freshly hashed password", async () => {
    const hash = await hashPassword("round-trip");

    expect(await comparePassword("round-trip", hash)).toBe(true);
    expect(await comparePassword("round-tri", hash)).toBe(false);
  });
});

describe("the 72-byte limit bcrypt does not tell you about", () => {
  it("caps at exactly the number of bytes bcrypt reads", () => {
    // Not a round number chosen for looks — past this, characters stop
    // counting, and the cap exists to keep "all of it counts" true.
    expect(MAX_PASSWORD_BYTES).toBe(72);
  });

  it("demonstrates why the cap is needed", async () => {
    const seventyTwo = "A".repeat(72);
    const hash = await hashPassword(seventyTwo + "-THIS-TAIL-IS-IGNORED");

    // Both of these are `true`, and that is the bug: a 92-character password
    // authenticates on its first 72 characters, so the last 20 are decoration.
    // Nothing in bcrypt reports this — it is why the limit is enforced before
    // the password ever reaches the hasher.
    expect(await comparePassword(seventyTwo, hash)).toBe(true);
    expect(
      await comparePassword(seventyTwo + "-COMPLETELY-DIFFERENT", hash),
    ).toBe(true);
  });
});
