/**
 * This file is reserved for entity-specific type aliases, extended types
 * (e.g., User with included relations), or domain types that are NOT
 * auto-generated by Prisma.
 *
 * It is intentionally empty right now — add exports here when a feature
 * branch needs a reusable type that goes beyond Prisma's generated types.
 *
 * Example future content:
 *   import type { User, Customer } from "../../generated/prisma/models";
 *   export type UserWithCustomer = User & { customer: Customer | null };
 */

export {};
